#!/bin/bash
echo "🚀 Cloudflare隧道安装指南"
echo "======================================="
echo ""
echo "由于网络问题，自动下载失败。请使用以下方法之一安装cloudflared："
echo ""
echo "方法1: 官方安装脚本"
echo "curl -fsSL https://pkg.cloudflare.com/cloudflared-stable-darwin-arm64.tgz | sudo tar -xzf - -C /usr/local/bin/"
echo ""
echo "方法2: 手动下载"
echo "1. 访问: https://github.com/cloudflare/cloudflared/releases/latest"
echo "2. 下载: cloudflared-darwin-arm64"
echo "3. 重命名为: cloudflared"
echo "4. 运行: chmod +x cloudflared"
echo ""
echo "方法3: 使用Homebrew"
echo "brew install cloudflare/cloudflare/cloudflared"
echo ""
echo "安装完成后，运行以下命令启动隧道："
echo "./cloudflared tunnel run --token eyJhIjoiNDcxNTkxNzQ5ZDJlZmMzODQwODIxZDgyYjJjYzRlMmQiLCJ0IjoiMjhhYjU4ZjMtZTFhYi00YmZiLWE2N2UtMWY1MzI2Y2ZlYjQxIiwicyI6IllUa3pNVE5tTm1JdFlqWXdPQzAwWlRWa0xXRm1aVFl0WkRZM01qUmpNMk0wWmpRdyJ9"
echo ""
echo "隧道启动后，translate.ease-joy.fun 就可以访问了！"